name: Set up gocovmerge
description: Install gocovmerge binary

inputs:
  destination:
    description: "Where to install the gocovmerge binary (default: $HOME/bin)"
    default: "$HOME/bin"
  version:
    description: "The gocovmerge version tag to install (e.g. v1.0.0)"
    default: latest

outputs:
  destination:
    description: Where the gocovmerge binary is
    value: ${{ steps.install.outputs.destination }}
  version:
    description: The installed version
    value: ${{ steps.install.outputs.version }}

runs:
  using: composite
  steps:
    - id: install
      shell: bash
      run: |
        mkdir -p "$HOME/bin"
        go install github.com/wadey/gocovmerge@latest

        # Add the Go bin path to GITHUB_PATH so future steps see it
        echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

        echo "destination=$(go env GOPATH)/bin/gocovmerge" >> "$GITHUB_OUTPUT"
        echo "version=latest" >> "$GITHUB_OUTPUT"
